# File: compose.dev.yaml
# Description: Dev sbom-in-a-box deployment with open ports for interfacing with locally running applications
#
# Author: Ian Dunn
# Author: Derek Garcia

name: sbom-in-a-box_development
services:
  # OSI container
  osi:
    container_name: osi_dev
    image: osi
    build: osi
    pull_policy: never  # use local build
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      start_period: 15s   # small delay to let startup scripts finish
      interval: 20s
      timeout: 5s
      retries: 3

  # MySQL server
  sbox_db:
    container_name: sbox_db_dev
    image: mysql:8.4.6
    command: --max_allowed_packet=32505856  # Set max_allowed_packet to 256M
    env_file:
      - path: .env
        required: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sbox
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?'MYSQL_ROOT_PASSWORD' must be set in the .env file}
      # create mysql user to use
      MYSQL_USER: ${MYSQL_USER:?'MYSQL_USER' must be set in the .env file}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?'MYSQL_PASSWORD' must be set in the .env file}
    volumes:
      - sbox_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 60s
      timeout: 5s
      retries: 3

  # SBOM-in-a-box API spring-boot application
  sbox_api:
    container_name: sbox_api_dev
    image: sbox_api
    build: .
    pull_policy: never  # use local build
    ports:
      - "8080:8080"
    env_file:
      - path: .env
        required: true
    environment:
      OSI_HOST: osi
      MYSQL_HOST: sbox_db
      MYSQL_DATABASE: sbox
      # create mysql user defined in the db
      MYSQL_USER: ${MYSQL_USER:?'MYSQL_USER' must be set in the .env file}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?'MYSQL_PASSWORD' must be set in the .env file}
    depends_on:
      sbox_db:
        condition: service_healthy
      osi:
        condition: service_healthy

volumes:
  sbox_db: