plugins {
    id 'java'
    id 'application'
}

group = 'org.svip'
version = '1.0.0-alpha'

jar {
    manifest {
        attributes(
                'Main-Class': 'org.svip.SBOMGeneratorCLI'
        )
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
            exclude '**/sbomfactory/generators/TestData**'
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
            exclude '**/sbomfactory/generators/TestData**'
        }
    }
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.18.3'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.19.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.19.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.19.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.19.2'
    implementation 'com.github.docker-java:docker-java-transport-httpclient5:3.5.3'
    implementation 'com.github.docker-java:docker-java:3.5.3'
    implementation 'com.google.guava:guava:33.4.8-jre'
    implementation 'com.mikemybytes:junit5-formatted-source-parent:1.0.1'
    implementation 'com.mikemybytes:junit5-formatted-source:1.0.1'
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    implementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    implementation 'net.sourceforge.jregex:jregex:1.2_01'   // Work around for Java regex limitations
    implementation 'org.cyclonedx:cyclonedx-core-java:10.2.1'
    implementation 'org.json:json:20250517'
    implementation 'org.apache.commons:commons-compress:1.28.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xlint:deprecation'
    options.compilerArgs << '-Xlint:unchecked'
}

tasks.named('javadoc') {
    source = sourceSets.main.allJava
    options.memberLevel = JavadocMemberLevel.PRIVATE
}
