tool: "cyclonedx-conan"
runtime_args:
  - "output_dir"
  - "manifest"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.3"
    format: "json"
    language:
      - "C"
      - "C++"
    commands:
      - "cyclonedx-conan {manifest} --output {output_dir}/cdxconan-cdx14.json"