profiles:
  - schema: "cyclonedx"
    spec_version: "1.3"
    format: "json"
    languages:
      - "C"
      - "C++"
    package_managers:
    commands:
      - "cyclonedx-conan {manifest} --output $SBOM_OUT/cdxconan-cdx14.json"