profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    language:
      - "Rust"
    package_manager:
    commands:
      - "cargo cyclonedx -f json -a -o $SBOM_OUT/cdxrust-cdx14.json"