source: "https://github.com/CycloneDX/cyclonedx-rust-cargo"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    languages:
      - "Rust"
    package_managers:
      - "Cargo"
    commands:
      - "cd *"
      - "cargo cyclonedx -f json"
      - "for dirname in ./crates/*; do mv $dirname/bom.json $SBOM_OUT/${dirname##*/}-cdxcargo-cdx14.json; done"