tool: "cyclonedx-conan"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.3"
    format: "json"
    language:
      - "C"
      - "C++"
    commands:
      - "cyclonedx-conan {manifest} --output $SBOM_OUT/cdxconan-cdx14.json"