tool: "cyclonedx-py"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    language:
      - "Python"
    commands:
      - "cyclonedx-py --format json -r -o {output_dir}/cdxpy-req-cdx14.json"
      - "cyclonedx-py --format json -p -o {output_dir}/cdxpy-poetry-cdx14.json"