source: "https://github.com/CycloneDX/cyclonedx-php-composer"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    languages:
      - "php"
    package_managers:
      - "Composer"
    commands:
      - "composer update --no-install"
      - "composer CycloneDX:make-sbom --output-format=JSON --output-file=$SBOM_OUT/cdxphp-14.json"