# Name of the tool
tool: "jake"
# Optional runtime args that must be defined before usage
runtime_args:
  - "output"
  - "manifest"
# > 1 ways to use the tool to generate sboms
profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    language:
      - "python"
    commands:
      - "jake sbom -t PIP -f {manifest} --output-format json -o {output}/jake-cdx14.json"