# Name of the tool
tool: "jake"
# > 1 ways to use the tool to generate sboms
profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    language:
      - "python"
    commands:
      - "jake sbom -t PIP --output-format json -o {output_dir}/jake-pip-cdx14.json"
      - "jake sbom -t POETRY --output-format json -o {output_dir}/jake-poetry-cdx14.json"