tool: "jbom"
runtime_args:
  - "output_dir"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.3"
    format: "json"
    language:
      - "Java_Jar"
    commands:
      - "java -jar /usr/local/bin/jbom.jar -d . -o {output_dir}"