profiles:
  - schema: "cyclonedx"
    spec_version: "1.5"
    format: "json"
    language:
      - "Rust"
    commands:
      - "sbom4rust --sbom cyclonedx -a osi-sbom --output-file=$SBOM_OUT/sbom4rust-cdx15.json"
  - schema: "spdx"
    spec_version: "2.3"
    format: "spdx"
    language:
      - "Rust"
    commands:
      - "sbom4python --sbom spdx -a osi-sbom --output-file=$SBOM_OUT/sbom4rust-spdx23.spdx"