profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    languages:
      - "C"
      - "C++"
      - "Dart"
      - "Erlang"
      - "Go"
      - "Haskell"
      - "Java"
      - "Javascript"
      - "PHP"
      - "Python"
      - "Ruby"
      - "Rust"
      - "Swift"
    commands:
      - "syft . -o cyclonedx-json@1.4=$SBOM_OUT/syft-cdx14.json"
  - schema: "spdx"
    spec_version: "2.3"
    format: "spdx"
    languages:
      - "C"
      - "C++"
      - "Dart"
      - "Erlang"
      - "Go"
      - "Haskell"
      - "Java"
      - "Javascript"
      - "PHP"
      - "Python"
      - "Ruby"
      - "Rust"
      - "Swift"
    commands:
      - "syft . -o spdx-tag-value=$SBOM_OUT/syft-spdx23.spdx"