tool: "syft"
runtime_args:
  - "output_dir"
profiles:
  - schema: "cyclonedx"
    spec_version: "1.4"
    format: "json"
    language:
      - "C"
      - "C++"
      - "Dart"
      - "Erlang"
      - "Go"
      - "Haskell"
      - "Java"
      - "Javascript"
      - "PHP"
      - "Python"
      - "Ruby"
      - "Rust"
      - "Swift"
    commands:
      - "syft . -o cyclonedx-json@1.4={output_dir}/syft-cdx14.json"
  - schema: "spdx"
    spec_version: "2.3"
    format: "spdx"
    language:
      - "C"
      - "C++"
      - "Dart"
      - "Erlang"
      - "Go"
      - "Haskell"
      - "Java"
      - "Javascript"
      - "PHP"
      - "Python"
      - "Ruby"
      - "Rust"
      - "Swift"
    commands:
      - "syft . -o spdx-tag-value={output_dir}/syft-spdx23.spdx"