name: Build and Test SBOM-in-a-Box
on:
  push:
  pull_request:
    branches: [ 'main', 'dev' ]  # PRs into main and dev trigger
jobs:
  build:
    runs-on: ubuntu-24.04
    # build with java 17 and 21
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build SBOM-in-a-Box
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          chmod +x gradlew
          # if PR or main/dev branch, run full build; otherwise skip tests
          if [[ "$EVENT_NAME" == "pull_request" || "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "dev" ]]; then
            ./gradlew build
          else
            ./gradlew build -x test
          fi
