name: Build and Test SVIP
on: 
  push:
      branches:  
      - 'dev'   # todo: replace with vars
      - 'main'  # todo: replace with vars
  pull_request:
    branches:  
      - 'dev'   # todo: replace with vars
      - 'main'  # todo: replace with vars
jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build and Test SVIP
        run: ./gradlew clean build
        
      - name: Store Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: "**/build/reports/"
          
      - name: Report Failure
        if: failure()
        run: echo "::error::Some Tests Failed, see the artifacts for details"
